#ifndef _H_DIAMETER_ERROR_CODE_
#define _H_DIAMETER_ERROR_CODE_
/*******************************************
	informational 
********************************************/
#define DIAMETER_MULTI_ROUND_AUTH         1001
/*******************************************
Success
*******************************************/
#define DIAMETER_SUCCESS                   2001
#define DIAMETER_LIMITED_SUCCESS           2002
/*******************************************
Protocol Errors
********************************************/
#define DIAMETER_COMMAND_UNSUPPORTED       3001
#define DIAMETER_UNABLE_TO_DELIVER         3002
#define DIAMETER_REALM_NOT_SERVED          3003
#define DIAMETER_TOO_BUSY                  3004
#define DIAMETER_LOOP_DETECTED             3005
#define DIAMETER_REDIRECT_INDICATION       3006
#define DIAMETER_APPLICATION_UNSUPPORTED   3007
#define DIAMETER_INVALID_HDR_BITS          3008
#define DIAMETER_INVALID_AVP_BITS          3009
#define DIAMETER_UNKNOWN_PEER              3010
/*********************************************
 Transient Failures
**********************************************/
#define DIAMETER_AUTHENTICATION_REJECTED   4001
#define DIAMETER_OUT_OF_SPACE              4002
#define ELECTION_LOST                      4003
//SR301 pkg HLR Report Sm add 
#define DIAMETER_ERROR_UNREACHABLE_USER    4221
#define DIAMETER_ERROR_DETACHED_USER       4223
/*******************************************
Permanent Failure
********************************************/
#define DIAMETER_ERROR_USER_UNKNOWN           5001
#define DIAMETER_UNKNOWN_SESSION_ID        5002
#define DIAMETER_AUTHORIZATION_REJECTED    5003
#define DIAMETER_INVALID_AVP_VALUE         5004
#define DIAMETER_MISSING_AVP               5005
#define DIAMETER_RESOURCES_EXCEEDED        5006
#define DIAMETER_CONTRADICTING_AVPS        5007
#define DIAMETER_AVP_NOT_ALLOWED           5008
#define DIAMETER_AVP_OCCURS_TOO_MANY_TIMES 5009
#define DIAMETER_NO_COMMON_APPLICATION     5010
#define DIAMETER_UNSUPPORTED_VERSION       5011
#define DIAMETER_UNABLE_TO_COMPLY          5012
#define DIAMETER_INVALID_BIT_IN_HEADER     5013
#define DIAMETER_INVALID_AVP_LENGTH        5014
#define DIAMETER_INVALID_MESSAGE_LENGTH    5015
#define DIAMETER_INVALID_AVP_BIT_COMBO     5016
#define DIAMETER_NO_COMMON_SECURITY        5017

// Experimental-Result 
#define DIAMETER_ERROR_ABSENT_USER           5550
#define DIAMETER_ERROR_USER_BUSY_FOR_MT_SMS        5551
#define DIAMETER_ERROR_FACILITY_NOT_SUPPORTED        5552
#define DIAMETER_ERROR_ILLEGAL_USER        5553
#define DIAMETER_ERROR_ILLEGAL_EQUIPMENT        5554
#define DIAMETER_ERROR_SM_DELIVERY_FAILURE  5555
#define DIAMETER_ERROR_SERVICE_NOT_SUBSCRIBED        5556
#define DIAMETER_ERROR_SERVICE_BARRED        5557
#define DIAMETER_ERROR_MWD_LIST_FULL        5558

typedef enum {
	RESULT_CODE_SUCCESS = 2001,
// Experimental-Result 
	RESULT_CODE_ERROR_USER_UNKNOWN = 5001,
	RESULT_CODE_ERROR_ABSENT_USER = 5550,
	RESULT_CODE_ERROR_USER_BUSY_FOR_MT_SMS = 5551,
	RESULT_CODE_ERROR_FACILITY_NOT_SUPPORTED = 5552,
	RESULT_CODE_ERROR_ILLEGAL_USER = 5553,
	RESULT_CODE_ERROR_ILLEGAL_EQUIPMENT = 5554,
	RESULT_CODE_ERROR_SM_DELIVERY_FAILURE = 5555,
	RESULT_CODE_ERROR_SERVICE_NOT_SUBSCRIBED = 5556,
	RESULT_CODE_ERROR_SERVICE_BARRE = 5557,
	RESULT_CODE_ERROR_MWD_LIST_FULL = 5558,
// End of Experimental-Result
	RESULT_CODE_LIMITED_SUCCESS = 2002,
	RESULT_CODE_MULTI_ROUND_AUTH = 1001,
	RESULT_CODE_COMMAND_UNSUPPORTED = 3001,
	RESULT_CODE_UNABLE_TO_DELIVER = 3002,
	RESULT_CODE_REALM_NOT_SERVED = 3003,
	RESULT_CODE_TOO_BUSY = 3004,
	RESULT_CODE_LOOP_DETECTED = 3005,
	RESULT_CODE_REDIRECT_INDICATION = 3006,
	RESULT_CODE_APPLICATION_UNSUPPORTED = 3007,
	RESULT_CODE_INVALID_HDR_BITS = 3008,
	RESULT_CODE_INVALID_AVP_BITS = 3009,
	RESULT_CODE_UNKNOWN_PEER = 3010,
	RESULT_CODE_AUTHENTICATION_REJECTED = 4001,
	RESULT_CODE_OUT_OF_SPACE = 4002,
	RESULT_CODE_ELECTION_LOST = 4003,
	RESULT_CODE_END_USER_SERVICE_DENIED = 4010,
	RESULT_CODE_TRANSIENT_USER_UNKNOWN = 4011,

	//SR301 pkg HLR Report Sm add 
	RESULT_CODE_UNREACHABLE_USER = 4221,
	RESULT_CODE_DETACHED_USER = 4223,

	RESULT_CODE_UNKNOWN_SESSION_ID = 5002,
	RESULT_CODE_AUTHORIZATION_REJECTED = 5003,
	RESULT_CODE_INVALID_AVP_VALUE = 5004,
	RESULT_CODE_MISSING_AVP = 5005,
	RESULT_CODE_RESOURCES_EXCEEDED = 5006,
	RESULT_CODE_CONTRADICTING_AVPS = 5007,
	RESULT_CODE_AVP_NOT_ALLOWED = 5008,
	RESULT_CODE_AVP_OCCURS_TOO_MANY_TIMES = 5009,
	RESULT_CODE_NO_COMMON_APPLICATION = 5010,
	RESULT_CODE_UNSUPPORTED_VERSION = 5011,
	RESULT_CODE_UNABLE_TO_COMPLY = 5012,
	RESULT_CODE_INVALID_BIT_IN_HEADER = 5013,
	RESULT_CODE_INVALID_AVP_LENGTH = 5014,
	RESULT_CODE_INVALID_MESSAGE_LENGTH = 5015,
	RESULT_CODE_INVALID_AVP_BIT_COMBO = 5016,
	RESULT_CODE_NO_COMMON_SECURITY = 5017,

	DELIVERY_FAILURE_MEMORY_CAPACITY_EXCEEDED  = 0,
	DELIVERY_FAILURE_EQUIPMENT_PROTOCOL_ERROR  = 1,
	DELIVERY_FAILURE_EQUIPMENT_NOT_SM_EQUIPPED  = 2,
	DELIVERY_FAILURE_UNKNOWN_SERVICE_CENTRE  = 3,
	DELIVERY_FAILURE_SC_CONGESTION  = 4,
	DELIVERY_FAILURE_INVALID_SME_ADDRESS  = 5,
	DELIVERY_FAILURE_USER_NOT_SC_USER  = 6,

	NO_PAGING_RESPONSE_VIA_THE_MSC = 0,	
	IMSI_DETACHED = 1,	
	ROAMING_RESTRICTION = 2,	
	DEREGISTERED_IN_THE_HLR_FOR_NON_GPRS = 3,	
	MS_PURGED_FOR_NON_GPRS = 4,	
	NO_PAGING_RESPONSE_VIA_THE_SGSN = 5,	
	GPRS_DETACHED = 6,	
	DEREGISTERED_IN_THE_HLR_FOR_GPRS = 7,	
	MS_PURGED_FOR_GPRS = 8,	
	UNIDENTIFIED_SUBSCRIBER_VIA_THE_MSC = 9,	
	UNIDENTIFIED_SUBSCRIBER_VIA_THE_SGSn = 10,
	DEREGISTERED_IN_THE_HSS_HLR_FOR_IMS = 11,
	NO_RESPONSE_VIA_THE_IP_SM_GW = 12,

	RESULT_CODE_DGW_TIMEOUT = 9001,
	RESULT_CODE_DGW_INTERNAL = 9002,
	RESULT_CODE_DGW_PEER_DISCONNECTED = 9003

}MME_ERROR_ENUM;
#endif
